<#
    Builds the two shipped projects in Release and packs the Vendavo packages.

    Requirements:
      - Visual Studio 2022 MSBuild and the .NET Framework 4.8 targeting pack
      - a NuGet client 5.0 or newer on PATH. The bundled tools/NuGet.exe is 2.8 and
        silently ignores the <license> and <repository> metadata this packaging relies on.
      - ErrorMessages.Designer.cs and TraceMessages.Designer.cs must exist. They are
        gitignored and generated by Visual Studio; without VS, generate them with:
          ResGen.exe ErrorMessages.resx SAML2.ErrorMessages.resources /str:cs,SAML2,ErrorMessages,ErrorMessages.Designer.cs /publicClass

    SAML2.Tests and SelfHostOwinSPExample are deliberately not built: they embed a dev
    certificate that upstream never committed (*.pfx is gitignored), so they cannot
    compile from a clean clone.
#>
[CmdletBinding()]
param(
    [string] $Configuration = "Release",
    [string] $OutputDirectory = (Join-Path $PSScriptRoot "artifacts")
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$srcRoot = Join-Path $repoRoot "src"

# Assembly identity that consumers bind to. Frozen at the version of the published
# upstream package so the patched assembly stays a drop-in replacement: Pricepoint has no
# binding redirect for SAML2.Core. Note that Saml2CoreNupkg.ps1 rewrites these attributes,
# so this check also catches that script having been run and left the tree dirty.
$expectedAssemblyVersion = "1.0.0.0"
$expectedFileVersion = "1.0.2.0"

function Get-MSBuild {
    $vswhere = Join-Path ${env:ProgramFiles(x86)} "Microsoft Visual Studio/Installer/vswhere.exe"
    if (-not (Test-Path $vswhere)) {
        throw "vswhere.exe not found at $vswhere. Install Visual Studio 2022 or set MSBuild manually."
    }

    $msbuild = & $vswhere -latest -products * -requires Microsoft.Component.MSBuild -find "MSBuild/**/Bin/MSBuild.exe" | Select-Object -First 1
    if (-not $msbuild) { throw "MSBuild not found via vswhere." }

    return $msbuild
}

function Get-NuGet {
    $nuget = Get-Command nuget -ErrorAction SilentlyContinue
    if (-not $nuget) {
        throw "No nuget client on PATH. Install NuGet 5+ (winget install Microsoft.NuGet) - the bundled tools/NuGet.exe 2.8 is too old for this nuspec."
    }

    $version = (& $nuget.Source help | Select-Object -First 1) -replace "[^0-9\.]", ""
    if ([version]($version.Split(".")[0..2] -join ".") -lt [version]"5.0.0") {
        throw "nuget $version is too old; 5.0 or newer is required for <license> and <repository> metadata."
    }

    return $nuget.Source
}

function Assert-Identity {
    param([string] $AssemblyPath)

    $name = [System.Reflection.AssemblyName]::GetAssemblyName($AssemblyPath)
    $file = (Get-Item $AssemblyPath).VersionInfo.FileVersion

    if ($name.Version.ToString() -ne $expectedAssemblyVersion) {
        throw "$($name.Name): AssemblyVersion is $($name.Version), expected $expectedAssemblyVersion. Check Properties/AssemblyInfo.cs."
    }
    if ($file -ne $expectedFileVersion) {
        throw "$($name.Name): AssemblyFileVersion is $file, expected $expectedFileVersion. Check Properties/AssemblyInfo.cs."
    }

    Write-Host "  $($name.Name) $($name.Version) (file $file)"
}

$msbuild = Get-MSBuild
$nuget = Get-NuGet

$projects = @(
    (Join-Path $srcRoot "SAML2.Core/SAML2.Core.csproj"),
    (Join-Path $srcRoot "Owin.Security.Saml/Owin.Security.Saml.csproj")
)

foreach ($project in $projects) {
    Write-Host "Building $(Split-Path $project -Leaf) ($Configuration)"
    & $msbuild $project "/p:Configuration=$Configuration" /t:Rebuild /v:minimal /nologo
    if ($LASTEXITCODE -ne 0) { throw "Build failed: $project" }
}

Write-Host "Verifying assembly identity"
Assert-Identity (Join-Path $srcRoot "SAML2.Core/bin/$Configuration/SAML2.Core.dll")
Assert-Identity (Join-Path $srcRoot "Owin.Security.Saml/bin/$Configuration/Owin.Security.Saml.dll")

New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null

foreach ($nuspec in Get-ChildItem -Path $PSScriptRoot -Filter "Vendavo.*.nuspec") {
    Write-Host "Packing $($nuspec.Name)"
    & $nuget pack $nuspec.FullName -OutputDirectory $OutputDirectory -NonInteractive
    if ($LASTEXITCODE -ne 0) { throw "Pack failed: $($nuspec.Name)" }
}
